### ISSUE TITLE
The UTC dates can be briefly seen in the page before they are replaced with the moment.js rendered timestamp.

### ISSUE THREAD

**Issue by miguelgrinberg** [miguelgrinberg/Flask-Moment#1]

**Comment by linys1987** [comment]
how to fix this problem?

**Comment by miguelgrinberg** [comment]
Well, this is a minor thing, so I haven't spent time looking at it. An idea that might work is to create these elements hidden in the DOM, and only make them visible once they have been initialized by moment.js.

**Comment by miguelgrinberg** [comment]
Addressed by #16.
