### ISSUE TITLE
It's using an older version of moment.js (2.5.1), with deprecated functions.

### ISSUE THREAD

**Issue by victorso** [miguelgrinberg/Flask-Moment#12]
Since the usage relies on the documentation provided by http://momentjs.com/docs/, it would be nice to upgrade from 2.5.1 to 2.9.0. Thanks.

**Comment by jeffwidman** [comment]
This can be closed, as it's been fixed for a while: https://github.com/miguelgrinberg/Flask-Moment/blob/master/flask_moment.py#L9
