### ISSUE TITLE
Add strftime formatting support

### ISSUE THREAD

**Issue by ncocacola** [miguelgrinberg/Flask-Moment#13]
Is there any way you could add support for formatting using the `strtime` format (e.g  `moment.strftime()`), for example by including `benjaminoakes/moment-strftime`?

This is what the [http://momentjs.com/docs/#other-tokens](`moment.js` documentation) suggests.

**Comment by miguelgrinberg** [comment]
I think I can come up with a mechanism that allows any plugins to be used, so it'll be up to you to include the plugin's js file, but after that, maybe you'll do something like this:

    {{ moment(my_time).plugin('strftime', '%H:%M:%D') }}

Would that work for you?

**Comment by ncocacola** [comment]
That would be great!

**Comment by miguelgrinberg** [comment]
This has been here for many years, so I'm going to close for now. If anybody is interested in implementing this option please open a new issue or PR.
