### ISSUE TITLE
How to use moment in macro?

### ISSUE THREAD

**Issue by greyli** [miguelgrinberg/Flask-Moment#29]
I have `{{ moment.include_moment() }}` in `base.html`, but when I use moment in a macro,  I get this error: `UndefinedError: 'moment' is undefined`.

**Comment by miguelgrinberg** [comment]
Does it work when you use it directly on the template, or does that also fail?

**Comment by greyli** [comment]
Yes, it worked outside the macro.

**Comment by wgwz** [comment]
@greyli can you provide a minimal example to reproduce?

**Comment by greyli** [comment]
By default, imported templates are not passed the current context. I solved this by using `{% from "macro.html" import foo with context %}`.  See doc [here](http://jinja.pocoo.org/docs/dev/templates/#import-context-behavior). 

Thanks anyway!
