### ISSUE TITLE
moment(from strptime) is off by 2 hrs

### ISSUE THREAD

**Issue by c0derabbit** [miguelgrinberg/Flask-Moment#31]
When I pass a `datetime.strptime(date)` date to moment, it adds 2 hours. I suspect a timezone issue, as it also says I'm UTC+02:00.  
`{{ moment(message.sent_at).format('LLL') }}` is rendered as May 15, 2017 **12:10 AM** 
while the same `{{ message.sent_at }}` becomes 2017-05-14 **22:10:00**.

Is there a timezone setting I'm missing?

**Comment by miguelgrinberg** [comment]
@c0derabbit in the `datetime.strptime(date)` expression, how did you set `date`?

**Comment by c0derabbit** [comment]
@miguelgrinberg it's a `datetime.now()` stringified, and stored in a sqlite3 db, something like this:
```py
d = datetime.now()
date = '{0}-{1}-{2}-{3}-{4}'.format(d.year, d.month, d.day, d.hour, d.minute)
```

**Comment by miguelgrinberg** [comment]
When you use `datetime.now()` you get a local time, without timezone information. Depending on the timezone configured on the server, you will get different universal times in this way. You should instead use `datetime.utcnow()`, which will give you uniform time units, regardless of server location.

After you switch to `utcnow()`, all your times stored in the database are going to be in UTC, which is good. Now any times you retrieve can be assumed to be UTC and given directly to moment, which also takes all times as UTC by default.

**Comment by c0derabbit** [comment]
Right, that makes sense & works too. Thanks!
