### ISSUE TITLE
Substract and add integration

### ISSUE THREAD

**Issue by fl0wx** [miguelgrinberg/Flask-Moment#35]
Hey is it possible to add the support for using moment().substraction(7, 'days') and add? Like in the official module?

Thanks a lot and kr
flow

**Comment by br0cky** [comment]
Another vote for this! Diff would be great as i was hoping to be able to compare dates e.g if date is older than x days...

**Comment by antmurph** [comment]
any update on this issue? Would be a great feature to have

**Comment by miguelgrinberg** [comment]
@antmurph if you'd like to have a go at it I'm happy to help. Eventually I'll get to it, but right now I don't have time unfortunately.

**Comment by antmurph** [comment]
@miguelgrinberg take a look at the PR, for my uses that works perfect.

**Comment by miguelgrinberg** [comment]
After some discussion in this and other issues I have decided I will not be adding add and substract, since this just perform calculations with dates and not formatting. If you need to add or substract dates, you can do it directly in Python.
