### ISSUE TITLE
Add SRI for better security

### ISSUE THREAD

**Issue by M0r13n** [miguelgrinberg/Flask-Moment#40]
It shouldn't be too complicated to add SRI to ensure that resources hosted on third-party servers have not been tampered with. Or am I missing something? 

Greetings

**Comment by miguelgrinberg** [comment]
Would you like to contribute a PR with this change?

**Comment by M0r13n** [comment]
I will see what I can do this weekend.

**Comment by miguelgrinberg** [comment]
This is already implemented. Closing.
