### ISSUE TITLE
Momentjs version

### ISSUE THREAD

**Issue by javl** [miguelgrinberg/Flask-Moment#49]
Before I started adding anything: you mentioned you want to Flask-Moment to reflect Momentjs as much as possible, without too many changes. It seems moment received some new functions in its version 2, that are not in Flask-Moment yet (like [toNow()](https://momentjs.com/docs/#/displaying/tonow/)). Would it be OK to wrappers for those functions? Seems default_moment_version is already at the right version for this.

**Comment by miguelgrinberg** [comment]
Yes, adding new functions is appreciated. Thank you for spending the time on this!

**Comment by javl** [comment]
I was mainly interested in adding the ```toNow()``` and ```to()``` functions, but they actually don't seem all that useful, as they're pretty much ``fromNow()`` in reverse; seems you can get the same results by swapping your dates around within the ```fromTime()``` function:
```moment().fromTime(past_timestamp)``` is the same as ```moment(past_timestamp).toNow()```
