### ISSUE TITLE
Blocked by CORS policy

### ISSUE THREAD

**Issue by androgeninc** [miguelgrinberg/Flask-Moment#51]
When using the {{ moment.include_moment() }} in chrome i get the below error message. Any idea how i can solve it? 

Importing moment through the <script src"..."></script> works fine, but then i can only use javascript-moment and not flask-moment.  

`Access to script at 'http://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment-with-locales.min.js' from origin 'http://127.0.0.1:5000' has been blocked by CORS policy: The response is invalid.`

**Comment by miguelgrinberg** [comment]
I'm not sure, I can access the moment js library at the URL above just fine. Maybe it was something temporary?

**Comment by androgeninc** [comment]
Still not working, but seems to be a browser issue and not a flask-moment issue, as it works fine in Firefox. Problem is only in Chrome. Understand it is not a code issue but any pointers would be appreciated.

**Comment by miguelgrinberg** [comment]
I don't think it is a browser issue, my guess is that it is a cdnjs issue, but I don't see it here so it isn't something I can debug. Maybe get a copy of the request and the response include all headers and contact them by writing an issue on their github at https://github.com/cdnjs/cdnjs/issues?

**Comment by androgeninc** [comment]
You seem to be right. It resolved itself magically on its own. Thanks for the reply!
