### ISSUE TITLE
Support for moment-timezone

### ISSUE THREAD

**Issue by dhhagan** [miguelgrinberg/Flask-Moment#53]
Does the current version argument support, or intend to support moment-timezone as well? If not, is there a known reason it wouldn't work? If not already supported and desirable, I can take a stab at it...

**Comment by miguelgrinberg** [comment]
I haven't tried it, but I believe if you load the moment-timezone js manually then you will be able to use Flask-Moment to render your timezone enabled dates/times. Happy to accept changes to enable it to work if you find that it doesn't.
