### ISSUE TITLE
Fix for out of sync in flask-moment

### ISSUE THREAD

**Issue by nehatharani** [miguelgrinberg/Flask-Moment#55]
Hi @miguelgrinberg, 

I have followed your tutorial very closely to learn the flask, Thank you for the wonderful content. 

I am having some trouble with flask-moment. Since the clocks are out of sync, moment.js has implemented a function to capture the offset and display the correct time. I have modified the moment.js accordingly. However, when I run the app it throws the error that function is not a part of flask-moment. How can I incorporate my new function in moment.js to flask-moment?  

JS function: 
```java
     pastFromNow : function (withoutSuffix) {
            var now = moment();
            var past = this < now ? this : now;
            return past.from(now, withoutSuffix);
        },
```
Mentioned [here:](https://github.com/jazzzz/moment/commit/97411a395d2f08d9b9c180176d034224b57320f4#diff-8c9255ccee4354533dcec358fb36d701)

I am using flask-appbuilder for creating my application.  

Any help will be appreciated. 

Thanks.,

**Comment by miguelgrinberg** [comment]
I'm not sure what problem you are having, but you should keep in mind that Flask-Moment is just a friendly wrapper around moment.js that allows you to use it from Flask templates. You don't have to always use the wrapper though, if you have made customizations to moment.js then you can just access this library directly using JavaScript.
