### ISSUE TITLE
How do I use format with refresh?

### ISSUE THREAD

**Issue by ChunYuan0930** [miguelgrinberg/Flask-Moment#56]
I'm add `{{ moment().format('LLL', refresh = True) }}` to my template,but it can't work.
BTW,I use fromNow(no_suffix=False, refresh = True) to be successful.

**Comment by miguelgrinberg** [comment]
Refresh only makes sense for relative times. When you are rendering a fixed timestamp refreshing does nothing, every refresh the same date is rendered.

**Comment by ChunYuan0930** [comment]
OK,thanks for your reply.
