### ISSUE TITLE
 AttributeError: 'str' object has no attribute '

### ISSUE THREAD

**Issue by whitesnow9291** [miguelgrinberg/Flask-Moment#62]
This works 
`<td>{{moment().format('MMMM Do YYYY, h:mm:ss a')}}</td>`
But this don't work
`<td>{{ moment('1/1/2020').format('L') }}</td>`
And can I ask other question?
Is result returned from executing raw sql query `db.engine.execute(sql)` and result from `User.query.all()` ?
Thanks

**Comment by miguelgrinberg** [comment]
You are calling `moment()` with a string argument, not a `datetime`.

I don't understand what is the 2nd question. Do you want to know if those two ways return the same result? It's the same data, but it is returned in different format. Working with models is more convenient.

**Comment by whitesnow9291** [comment]
Originally, I passed value returned from db.engine.execute to moment.
This is what I tried actually.
In view.py

```
sql = text('SELECT * from users')
users = db.engine.execute(sql)
return render_template('users.html', users=users)
```

In Jinja2 template
```
{% for u in users %}
<tr>
   <td>{{u.name}}</td>
   <td>{{moment(u.member_since).fromNow()}}</td> # this line return error as issue title
   <td>{{ u.member_since }} </td> # this line works, but it's unformatted date, so I want to format using moment
</tr>
{% endfor %}
```

Thanks

**Comment by miguelgrinberg** [comment]
Still don't understand why you mix raw SQL with SQLAlchemy. If you want to use the model objects then you have to use the high-level queries, the SQL calls know nothing about models.

**Comment by whitesnow9291** [comment]
Ok, I understand. thanks
