### ISSUE TITLE
Request the js files to be retrieved over https from the CDN

### ISSUE THREAD

**Issue by greendinosaur** [miguelgrinberg/Flask-Moment#64]
When running my app locally in development, it's running under http. This means the js files referenced by Flask-Moment are retrieved over http. This is causing problems when I run some checks with the Lighthouse tool in Chrome Dev Tools. I'd like to be able to force the js references to be via https and not via http.

I propose making a change to `include_moment` with an optional variable of force_https. The default will be false and the function will work as at present and use whatever the application is running under. If it's set to true then it will use https irrespective of what the application is running.

**Comment by miguelgrinberg** [comment]
I think it would be okay if we always use https:// for the js dependencies, without a setting. If you make this change and send a PR I'll merge it. Thanks!

**Comment by greendinosaur** [comment]
okay, will give it a go.

**Comment by greendinosaur** [comment]
Thanks!
