### ISSUE TITLE
Looking for Converted Value Only (not wrapped in span tag)

### ISSUE THREAD

**Issue by bfaivre** [miguelgrinberg/Flask-Moment#66]
Is it possible to get the timestamp converted and formatted without being wrapped in a span tag? If not, do you have a recommended way to extract this? I'm looking to use it in a placeholder for an input. Thanks in advance.

**Comment by miguelgrinberg** [comment]
Not from Jinja, but you can always use JavaScript to generate your placeholder content.

**Comment by bfaivre** [comment]
Thanks @miguelgrinberg.

**Comment by lanmaster53** [comment]
I have a similar issue. I'm trying to pre-populate the `value` attribute of a `date` input field with a time from the server converted to local using Moment. It doesn't look like the extension is built to do this, but I'm not sure how I would even go about it. Any thoughts on how to accomplish this, preferably with the Flask-Moment extension?

**Comment by miguelgrinberg** [comment]
@lanmaster53 in your Jinja template you can generate a JS variable with the server time:

```
<script>
    const serverTime = '{{ your_python_time.isoformat }}';
    // rest of the JS logic here
</script>
```
