### ISSUE TITLE
Apparently the CDN is giving 404 for the moment.js version in the package

### ISSUE THREAD

**Issue by guillermohs9** [miguelgrinberg/Flask-Moment#68]
Hi! I'm getting 

    DevTools failed to load SourceMap: Could not load content for http://cdnjs.cloudflare.com/ajax/libs/moment.js/2.26.0/moment-with-locales.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

on the browser console with latest Flask-Moment installed (0.10). The latest version on cdnjs for moment.js is 2.29.1.
Cheers!

**Comment by miguelgrinberg** [comment]
This is a failure on the source map, not on the library itself. Also I do not understand why you get a request for the 2.26 version of moment, since the latest version of Flask-Moment uses 2.29.1. You may want to invalidate your browser cache, maybe that's the problem.

**Comment by guillermohs9** [comment]
I deleted the cache and tried incognito and I still see it. It's probably some other library  or something else I'm missing. Sorry for this issue.

**Comment by 1wonjae** [comment]
It is Flask-Moment, it's just that if you install from PyPi you get the June 10 release (0.10). I did the same and see the source code having 2.26.0 as default.

**Comment by miguelgrinberg** [comment]
Sorry, my bad, it appears I never released the last batch of changes. Release 0.11 is now on PyPI.
