### ISSUE TITLE
can't call moment.include_moment() from within Python code

### ISSUE THREAD

**Issue by coreybrett** [miguelgrinberg/Flask-Moment#76]
If I call moment.include_moment() inside a Jinja template, it works fine, but if I try to call it directly from Python code, I get `AttributeError: 'Moment' object has no attribute 'include_moment'`

I am experimenting with Dominate as a possible replacement for Jinja.

**Comment by miguelgrinberg** [comment]
What you are trying to do is not currently supported, this extension is designed to work with Jinja templates. You can only do this if you find the internal state of the extension:

    current_app.extensions['moment'].include_moment()

But this is not something that is supported. It can change at any time and without previous notice.
