### ISSUE TITLE
version 1.0.0 breaks import

### ISSUE THREAD

**Issue by schaarj** [miguelgrinberg/Flask-Moment#80]
After building a new image that depends on Flask-Moment I suddenly get import errors
**Installed Version:**
```
$ pip freeze
...
Flask-Moment==1.0.0
...
```
**Error**:
```
  File "/home/flask/digimat/app/__init__.py", line 12, in <module>
    from flask_moment import Moment
ModuleNotFoundError: No module named 'flask_moment'
```
I tested upgrading Flask-Moment in other environments all with the same effect

**Comment by miguelgrinberg** [comment]
Sorry about that. I knew I was going to mess something up with a release that has so many changes in it. :)

I put out 1.0.1 with a fix. Please let me know if that continues to give you trouble.

**Comment by schaarj** [comment]
No works like a charm, Thanks for the quick fix and all your other work on flask as well :)
