### ISSUE TITLE
I keep getting errors trying to format a duration

### ISSUE THREAD

**Issue by alxcnwy** [miguelgrinberg/Flask-Moment#82]
I'd like to format a number of seconds e.g. 150 seconds -> 00:02:30 using Flask-Moment

I think this should work:
```
{{ moment().startOf('day').seconds(s).format('H:mm:ss'); }}
```

but I get an error `jinja2.exceptions.UndefinedError: 'flask_moment._moment object' has no attribute 'startOf'`

**Comment by miguelgrinberg** [comment]
There is no `startOf` or `seconds` functions in Flask-Moment. You are writing Python code here, not moment.js in JavaScript. See the documentation for the list of operations that are supported.
