### ISSUE TITLE
Manually reload flask_moment_render_all when new content is loaded

### ISSUE THREAD

**Issue by kingkong-cmd** [miguelgrinberg/Flask-Moment#83]
I am using htmx to async load some components onto my page. The components gets loaded when in view, so it may be some time after the actual pageload. These components includes dates that I would like to render with moment. Is there any way I can re-run the flask_moment_render_all function  so that these dates are being caught as well?

**Comment by miguelgrinberg** [comment]
Have you seen the documentation? Specifically this: https://flask-moment.readthedocs.io/en/latest/advanced.html#ajax-support

**Comment by kingkong-cmd** [comment]
Apologies, I thought I had. I see it is even included in the example app. Thank you!
