### ISSUE TITLE
flask-moment doesn't seem to be rendering my time if I use jinja-partials

### ISSUE THREAD

**Issue by djotaku** [miguelgrinberg/Flask-Moment#93]
I'm using jinja partials (from Mike Kennedy) and htmx to create this app for myself: https://github.com/djotaku/taskwarrior_web/tree/main

I'm specifically using it here: https://github.com/djotaku/taskwarrior_web/blob/cd2c95ff7f15a7a422934fa40f37f7f3332d8560/taskwarrior_web/templates/partials/task_table.html

With the flask-moment in the header of https://github.com/djotaku/taskwarrior_web/blob/cd2c95ff7f15a7a422934fa40f37f7f3332d8560/taskwarrior_web/templates/layout.html

When I first load my page, it looks correct:

![moment_works_on_first_load](https://github.com/miguelgrinberg/Flask-Moment/assets/2624194/8e9e9b85-fc00-430b-b716-feed5338c25a)

 but after I click one of the buttons which uses the jinja_partial to render a new table, it no longer does the moment conversion. 

![moment_no_longer_works](https://github.com/miguelgrinberg/Flask-Moment/assets/2624194/d6e21005-d9e3-4391-9745-82c52ed88462)

Is there something extra I need to do so that it works together with jinja-partials?

**Comment by miguelgrinberg** [comment]
See the [Ajax section](https://flask-moment.readthedocs.io/en/latest/advanced.html#ajax-support) of the documentation. Whenever you load moment timestamps asynchronously you have to call `flask_moment_render_all()` in the browser to render those newly added timestamps.

**Comment by djotaku** [comment]
Thanks, that's exactly what I needed
